geerlingguy/drupal-vm

- example.drupal.make.yml
It seems like Drush is fine with some non-quoted property values, but has problems with others. Here is an example where I modified this default make file and ended up with problems:
https://gist.github.com/mchelen/0a2aa697ca208e94c684
For the sake of consistency, maybe it is best to use quotation marks for all values?
> Use quotation marks for property values

- README.md
I initially tried "drupal/drupal" for a username and password combo since it was used for MySQL credentials, but I didn't see anywhere where the Drupal admin credentials were mentioned. This final part could be a little confusing for people just getting into setting up VM local development like myself.
> Clarify credentials for logging into site

- README.md
Not every host machine has NFS kernel server installed. I got stuck here several times using Ubuntu 14.04 as host, prompting to error:
```js
==> drupaldev: Destroying VM and associated drives...
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/mixin_synced_folders.rb:113:in `block in synced_folders': Internal error. Report this as a bug. Invalid: nfs (RuntimeError)
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/mixin_synced_folders.rb:101:in `each'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/mixin_synced_folders.rb:101:in `synced_folders'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/synced_folder_cleanup.rb:19:in `call'
```
In some cases, it prompts to ask root …
> add NFS server as Dependency

- example.config.yml
I've been running into db issues related to permissions when using the drupal vm with existing projects. This affects the drupal site installer (if you want to use it and name the db anything other than "drupal"), as well as drush from the host OS (connection issues). This PR fixes the problems for me.
> Made drupal_mysql_database a variable

- Vagrantfile
This recycles the available `config.yml` settings and makes them work with Parallels Desktop if `parallels` is chosen as the provider.
> Add Parallels Desktop support.

- example.drupal.make.yml
Getting a working copy of the drupal project means you always get the default branch.
You should never specify `version` on git downloads, only branches or commits.
> Improved example

- Vagrantfile
When trying to run a Vagrant command (e.g. "vagrant ssh") from a different directory in the project aside from the root one where the Vagrantfile lives, the command will fail even though config.yml exists.
> Path: /Users/opdavies/Code/Current/Personal/dcbristol15/Vagrantfile
Message: Configuration file not found! Please copy example.config.yml to config.yml and try again.
I've added some extra code to Vagrantfile to make sure that we're looking in the correct place for config.yml, rather than in the directory that we're in when we run the command.
> "config.yml missing" even when it exists

- Vagrantfile
I wanted to include this repository as a sub directory in my own project and delegate the Vagrantfile from my project root.
```ruby
dir = File.dirname(__FILE__) + '/'
load dir + "drupal-vm/Vagrantfile"
```
Currently this does not work as the provisioning paths are relative.
> Allow Vagrantfile to be loaded from separate script

- example.config.yml
- provisioning/playbook.yml
- provisioning/requirements.txt
Relates to https://github.com/geerlingguy/drupal-vm/issues/137
> Add Selenium and Firefox to vm to power Behat tests

- Vagrantfile
I read your article about rsync vs nfs–a very interesting read. I tried switching to it but in the end I decided to stick to NFS due to the long sync delays (annoying while editing css for example).
To get instant sync (and hopefully some other performance benefits) I needed to add the following mount options to the synced_folders `nolock,vers=3,udp,noatime,actimeo=1'`
Hence this patch.
> add support for custom synced folder mount options

- README.md
- example.config.yml
Today I started exploring your Drupal VM project: awesome! Works perfectly so far. In the process I encountered a few documentation links which pointed to your Github wiki. However, I saw you recently moved the documentation, so I updated a few links to go directly to the [Drupal VM documentation site](http://docs.drupalvm.com).
> Update documentation links

- README.md
- Vagrantfile
This update makes a small modification to the Vagrantfile to detect if the user has the vagrant-auto_network plugin installed and uses that to automatically assign an IP address to the VM rather than having to explicitly set an IP in the config.yml file.  This is useful for users that need to run multiple VM as it helps avoid IP address collisions or having to track which IPs are used by which VMs.
> vagrant-auto_network plugin support

- docs/extras/pimpmylog.md
- docs/extras/xhprof.md
Updates the documentarians for xhprof and pimpmylog extras. The vhost aliases have changed at some point from the http://local. urls and the supporting documentation should match.
> Update documentation for xhprof and pimpmylog urls

- example.config.yml
```
Exception 'Drupal\Core\Installer\Exception\InstallerException' with message 'Xdebug settings: xdebug.max_nesting_level is set to 255.
Set xdebug.max_nesting_level=256 in your PHP configuration as some pages in your Drupal site will not work when
this setting is too low.' in /var/www/drupal/core/includes/install.core.inc:2292
```
> Avoid Drupal installer exception for xdebug nesting level

- example.config.yml
mySQL's default wait timeout is crazy high. (see also http://www.eliotk.net/12/21/mysql-wait_timeout-default-is-set-too-high/)
No need to keep connections open for 8 hours by default.
I thought about putting this in the mysql playbook as a default, but since it _is_ mySQL's default, I figured this makes more sense.
> Set example mysql_wait_timeout to 300.

- example.config.yml
Today I ran into the extra_packages variables in my config.yml file. I had a hunch that it could be of use to me, but I had to track it back a bit to `provisioning/tasks/extras.yml` and to [this ticket](https://github.com/geerlingguy/drupal-vm/issues/62) to understand what it exactly does. 
In my case it was perfect to provision the unzip package (for usage in downloading libraries by Drush make files). So, I propose to add a bit more explanation to the variable to make it more clear on how to use it and what it expects.
> Add a bit more explanation to the extra_packages variable

- provisioning/templates/drupalvm.aliases.drushrc.php.j2
The ansible vagrant plugin automatically writes an inventory file with the ssh-config options needed to connect to the vm instance. When one has more than 1 VMs running on the host the chance in this PR will ensure that vagrant provision will still work.
Inventory file sits at .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory
There's also a "ansible_ssh_host" variable which I suspect would be a better fit for the 'remote-host' value rather than what we have now? This would mean that even if one does not setup their hosts file on the host, drush aliases will still work for that website.
> Pass the port number from the Vagrant autogenerated inventory

- example.config.yml
- provisioning/tasks/install-site.yml
Would be useful to allow additional arguments to be passed to the `drush site-install` command.
In my case I'd like to install the commerce kickstart distribution without the demo store.
> Add drupal install arguments configuration option

- README.md
Simple change to display the DrupalVM using markdown.
Seemingly not needed, but the logo will then display OK on Bitbucket.
> Display DrupalVM logo using Markdown.

- README.md
- docs/other/windows.md
Added details to resolve https://github.com/geerlingguy/drupal-vm/issues/231
> Added PowerShell details for Windows 7

- provisioning/templates/drupalvm.aliases.drushrc.php.j2
Reverts geerlingguy/drupal-vm#202
See rationale in https://github.com/geerlingguy/drupal-vm/issues/259
> Revert "Pass the port number from the Vagrant autogenerated inventory"

- docs/other/php-7.md
Removed "PHP 7 is out soon" comments from PHP 7 documentation page .
PHP 7.0.0 is out now! HURRAH!
> Remove PHP 7 RC comments from docs

- Vagrantfile
- docs/extras/syncing-folders.md
I mentioned this earlier in https://github.com/geerlingguy/drupal-vm/issues/189#issuecomment-139809306.
This would allow the user to override any option passed to `config.vm.synced_folders`. By default it would still work exactly as is does now. Currently I'm using these options for most of my projects for better file permissions using rsync (the merge is not deep by choice, so that you can eg remove specific `rsync__args`).
```rb
options_override:
rsync__chown: false
rsync__verbose: true
rsync__args: [
"--verbose", "--archive", "--delete",
"--chmod=Dgu=rwx,Do=rx,Fgu=rw,Fo=r", # 664 for files, 775 for directories
"--owner", "--group", # required for the following command
"--usermap=*:vagrant", "--groupmap=*:www-data,*:apache",
]
```
> add support for overriding any synced_folder option

- docs/deployment/drush-make.md
- docs/deployment/local-codebase.md
- docs/deployment/multisite.md
- docs/extras/behat.md
- docs/extras/drupal-console.md
- docs/extras/drush.md
- docs/extras/mailhog.md
- docs/extras/nodejs.md
- docs/extras/solr.md
- docs/extras/syncing-folders.md
- docs/other/cloning-with-newd.md
- docs/other/linux.md
- docs/other/php-7.md
- docs/other/webservers.md
- docs/other/windows.md
Worth reviewing as I removed some docs that I figured wasn't supported anymore (mentioned in commit messages):
- Long paths on Windows with Vagrant 1.7
- Symbolic links on CentOS 6 as we dont symlink the docroot anymore.
> Clean up and bring docs up to date with latest example configurations

- .gitignore
- Vagrantfile
- docs/other/local-vagrantfile.md
- mkdocs.yml
See https://github.com/geerlingguy/drupal-vm/pull/343
@Tigatok I credited you on the docs as this was your research and instructions. I simplified it a bit as users can add whatever configurations they want now, not just what Drupal VM choses to expose. Does it look okay to you?
> Add support for sourcing a local Vagrantfile

- example.config.yml
This way the user would either leave it as a string, or maybe remember that it used to be a string when it fails. If you set `drush_version: "7"` it would still fail though as this is not the name of the branch (nor a tag).
> TASK [geerlingguy.drush : Clone Drush from GitHub.] ****************************
fatal: [drupalvmv]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to checkout 7"}
Now the error messages would at least help them figure it out. But maybe it's even worth adding a comment about it being a branch, and _not_ a version :)
> Helps with #379: Set drush_version explicitly to a string

- Vagrantfile
- docs/other/base-os.md
- example.config.yml
- provisioning/tasks/init-debian.yml
- provisioning/tasks/init-redhat.yml
Related PR/Issues:
- https://github.com/geerlingguy/drupal-vm/pull/184
- https://github.com/geerlingguy/drupal-vm/issues/257
This is really a second variation of #184 that's more generalised and supports jinja variables in any config value (as well as variables pointing to other variables: `servername: "{{ drupal_domain }}"` -> `drupal_domain: "{{ vagrant_machine_name }}"`).
[Beetbox](https://github.com/drupalmel/beetbox/blob/master/Vagrantfile#L38:L43) does something similar, but I added a recursive walker so we can support nested hashes/lists etc.
> PR #184, Issue #257: Add support for jinja variables in `config.yml` replacing hardcoded hosts and paths

- example.config.yml
Hups! I did my last batch of testing with another `config.yml` so didn't catch this! `vagrant_machine_name` is by default set to _drupalvm_ while the `vagrant_hostname` is _drupalvm.dev_
> Follow-up #410: Use vagrant hostname instead of machine name for servernames

- docs/other/php-7.md
- example.config.yml
Hey, i was just trying to follow http://docs.drupalvm.com/en/latest/other/php-7/ and found that no matter what during initial provision i am getting errors like:
```
TASK [geerlingguy.php : Configure php-fpm pool (if enabled).] ******************
failed: [pm8] => (item={u'regexp': u'^listen.?=.+$', u'line': u'listen = 127.0.0.1:9000'}) => {"failed": true, "item": {"line": "listen = 127.0.0.1:9000", "regexp": "^listen.?=.+$"}, "msg": "Destination /etc/php5/fpm/pool.d/www.conf does not exist !", "rc": 257}
failed: [pm8] => (item={u'regexp': u'^listen\\.allowed_clients.?=.+$', u'line': u'listen.allowed_clients = 127.0.0.1'}) => {"failed": true, "item": {"line": "listen.allowed_clients = 127.0.0.1", "regexp": "^listen\\.allowed_clients.?=.+$"}, "msg": "Destination …
```
> Update to php-fpm configuration for PHP 7

- provisioning/templates/nginx-vhost.conf.j2
Use the nginx vhost template to use `php_fpm_listen` rather than hard-coding it into the template.
I've also opened a PR upstream to update this variable for Debian/Ubuntu servers. https://github.com/geerlingguy/ansible-role-php/pull/78
> Use php_fpm_listen

- .travis.yml
- example.config.yml
- provisioning/tasks/build-makefile.yml
- provisioning/tasks/drush-aliases.yml
- tests/Dockerfile.centos-6
- tests/Dockerfile.centos-7
- tests/Dockerfile.ubuntu-12.04
- tests/Dockerfile.ubuntu-14.04
- tests/centos-6-vars.yml
- tests/centos-7-vars.yml
I realised that we probably can't integrate these for a while due to stuff like https://github.com/geerlingguy/ansible-role-php-xhprof/issues/8, but I thought I'd send it over for some brainstorming.
1. I came up with at least a temporary solution for moving the `drush_makefile` to the VM before running it, instead of relying on it being a _vagrant_ environment. If https://github.com/geerlingguy/drupal-vm/pull/378 gets merged, we should pass the `host_project_root` var to ansible and use that instead. This issue was identified earlier in #84.
2. Also re-arranged the order of how drush files are generated so if run locally at least the local alias will be kept instead of overridden by an invalid remote alias.
3. Besides that I added some basic sanity checks to see that some of the stuff in …
> Use Docker-based Travis CI tests for multi-platform support

- README.md
**Not ready to be merged** yet as we should wait for Vagrant 1.8.2 so that `ansible_local` works reliably.
I mentioned that it's tested under 1.8.2 as of February 2016, so let's hope it gets released by then :)
> Bring README.md up to date. Closes #357

- .travis.yml
- example.config.yml
- provisioning/playbook.yml
- provisioning/tasks/dashboard.yml
- provisioning/templates/dashboard.html.j2
- provisioning/templates/drupalvm-local.aliases.drushrc.php.j2
- provisioning/templates/drupalvm.aliases.drushrc.php.j2
- provisioning/vars/main.yml
First take at a dashboard mentioned in #320. I'm not sure how we would want to add this to the webserver actually? At the moment it doesn't work :smile: It works if you set `apache_remove_default_vhost: false` hehe
Also I've only tested minimally (only apache for example).
I used bootstrap so this wouldn't work if the user is offline. I feel that's still okay (the stylesheet is loaded at the end of the document not to pause the rendering), maybe add some minimal styling for such cases.
One minor hack is the `Adminer` link for each database. This links to `adminer.drupalvm.dev/?username=root&db=drupal`, which is actually an auto-login feature, but it fails due to not being configured. Instead it redirects the user back to login screen with an error message _AND_ also pre-fills the fields.
> [WIP] Issue #320: add a dashboard

- docs/extras/ssl.md
- mkdocs.yml
Is there any other way to transfer the certificate?
```sh
vagrant up
^Ctrl-C
vagrant ssh -c 'sudo mv /vagrant/example.cert ...'
vagrant provision
```
Just worried about suggesting something potentially dangerous if people use it for other things than simply testing SSL.
> Issue #349, #162: Add SSL docs

- Vagrantfile
This enables users to choose between using vagrant-hostsupdater and vagrant-hostmanager. See #444
> Add support for vagrant-hostmanager plugin.

- .travis.yml
- Vagrantfile
A rebase of #292. Also added rubocop check to travis.
According to https://docs.travis-ci.com/user/ci-environment/#Runtimes we do not need to specify the language as ruby because it's always installed.
> Rebase of #292 Ruby coding style fixes via rubocop in Vagrantfile

- Vagrantfile
- provisioning/templates/dashboard.html.j2
- provisioning/templates/drupalvm-local.aliases.drushrc.php.j2
- provisioning/templates/drupalvm.aliases.drushrc.php.j2
- provisioning/templates/nginx-vhost.conf.j2
**Needs manual testing** I'm on an even slower connection today, so wont be able to test it until some other day.
- This fixes: #479
- Simplifies the alias logic in `Vagrantfile`
- Support nginx aliases as well as redirects for hostsupdater/hostsmanager
- Fixes dashboard hosts entry logic never to ignore hosts, only ignore hosts when the entry becomes `192.168.88.88 192.168.88.88` (dashboard).
- Fixes broken drush aliases when nginx aliases are used.
I do not create drush aliases for every host alias intentionally. Only the first one will be used.
> Fix various alias issues in dashboard, hostsupdater and drush aliases

- provisioning/tasks/init-debian.yml
PPA - https://launchpad.net/~ondrej/+archive/ubuntu/php-7.0 has been replaced by https://launchpad.net/~ondrej/+archive/ubuntu/php which supports both PHP 5.6 & 7
Fixes #491
> Updated PHP7 PPA.

- provisioning/templates/drupalvm.vcl.j2
> Issue #397: Add basic Varnish cache tag support with BANs.

- provisioning/templates/drupalvm.aliases.drushrc.php.j2
`~` expansion is a shell feature that doesnt work with rsync -e flag.
> Fix drush core-rsync not expanding ~ to $HOME

- example.config.yml
- provisioning/playbook.yml
First approach—allow scripts to be run prior to role installation... note that this means things like Git aren't guaranteed to be available, and pre-provision scripts would need to at a minimum install any required dependencies before running.
If a script needs other dependencies present, it may be best to use a post provision script instead...?
> Fixes #598: Add support for pre_provision_scripts.

- provisioning/tasks/install-site.yml
Related #500 #605.
Before:
> TASK [Install Drupal with drush.] **********************************************
fatal: [drupalvm_tester]: FAILED! => {"failed": true, "msg": "The conditional check ''Successful' not in drupal_site_installed.stdout' failed. The error was: error while evaluating conditional ('Successful' not in drupal_site_installed.stdout): Unable to look up a name or access an attribute in template string. Make sure your variable name does not contain invalid characters like '-'.\n\nThe error appears to have been in '/Users/cindy/Projects/Personal/drupalvm-varnish/provisioning/tasks/install-site.yml': line 13, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install Drupal with drush.\n  ^ …
> Fix misleading error message when attempting to install drupal without a codebase

- example.config.yml
- provisioning/tasks/cron.yml
This is mostly a security measurement for users provisioning a production environment.
> Issue #614: Install cron jobs as the SSH user instead of as root

- Vagrantfile
- docs/other/overriding-configurations.md
- mkdocs.yml
- provisioning/playbook.yml
This is a proof of concept that doesn't require Ansible 2.
New config loading logic:
1. `config.yml`
2. Include any files referenced in `extra_configs` list.
3. If available, and running through Vagrant, include `local.config.yml`
4. If available, and running directly through ansible, include `prod.config.yml`
If someone uses a vagrant plugin for deploying, such as for aws, they can add `env: prod` variable to their `config.yml` to include the prod config instead of the local config. Maybe this isn't a necessary feature?
I'm also assuming this would make #378 more difficult.
Edit: I simplified the PR to only support `local.config.yml` and `prod.config.yml`, both of which are included if available. Include order goes: `config.yml`, `prod.config.yml`, `local.config.yml`.
> [WIP] Add support for local.config.yml

- docs/other/php-56.md
This pull request solves the issue #635 adding the php_fpm_pool_conf_path configuration for PHP 5.6 documentation.
> Issue #635: Documentation for PHP 5.6 does not have php_fpm_pool_conf_path

- provisioning/playbook.yml
- provisioning/tasks/cron.yml
So turns omit `with_items` did not like `omit`. Unlike `with_fileglob` which had no issue. I guess it's because `with_fileglob` doesnt fail with 0 matches.
Falling back to an empty list works for `with_items` though.
> Issue #641: Fix so that optional variables are in fact optional

- docs/other/php-56.md
Adding php5-apcu would be consistent with the default php role "php_enable_apc: true" value.
> Docs: Install php5-apcu. [ci skip]

- .travis.yml
- README.md
- default.config.yml
- docs/deployment/composer.md
- example.drupal.composer.json
- mkdocs.yml
- provisioning/playbook.yml
- provisioning/tasks/build-composer-project.yml
- provisioning/tasks/build-composer.yml
- provisioning/tasks/build-makefile.yml
- tests/ubuntu-16-nginx.config.yml
Issue #506. This is still WIP, just checking travis' opinion.
> Issue #506: Add support for composer based site builds

- default.config.yml
- tests/ubuntu-16-nginx.config.yml
@geerlingguy would you mind testing this to see how the performance has improved since https://github.com/geerlingguy/drupal-vm/pull/694#issuecomment-223688740?
> Use composer project based site build as the default

- Vagrantfile
I think we've had a few of these issues as well and this makes it super clear
> This Vagrant environment has specified that it requires the Vagrant
version to satisfy the following version requirements:
> \>= 1.8.1
> You are running Vagrant 1.x.x, which does not satisfy
these requirements. Please change your Vagrant version or update
the Vagrantfile to allow this Vagrant version. However, be warned
that if the Vagrantfile has specified another version, it probably has
good reason to do so, and changing that may cause the environment to
not function properly.
> Issue #709: Add strict vagrant version requirement for easier debugging

- default.config.yml
https://github.com/geerlingguy/ansible-role-nodejs/issues/29
> Set node global install dir to a location writable by vagrant

- default.config.yml
Maybe not such a useful feature but I add this to almost every project so I don't need to worry if the site was configured to redirect to `www` or not. Thought I'd send over a PR in case interested.
> Add www.drupalvm.dev as a default webserver alias

- default.config.yml
> Clearer comments: required vars in default.config sounded optional

- default.config.yml
- provisioning/tasks/sshd.yml
cd to `drupal_core_path` when SSHing to the VM. #661 
*note: this will be ignored if not set and fail gracefully if the path doesn't exist.
> Set ssh_home as default pwd for SSH.

- provisioning/templates/dashboard.html.j2
@geerlingguy 
A re-branch of the solution presented in #721 - Also, seems to address the issue presented in #685
> Fixes dashboard and vagrant_ip zeroes issue

- provisioning/templates/nginx-vhost.conf.j2
From Using https on nginx #754
The provisioning/templates/nginx-vhost.conf.j2 template did not support the extra_parameters as in the template for ansible-role-nginx
> Support including extra_parameters for nginx vhosts

- docs/other/php-56.md
> DOCS: Set vagrant_box to ubuntu1404 for PHP 5.6

- provisioning/templates/dashboard.html.j2
> Fixes #795, broken Your Site links on dashboard.

- default.config.yml
- docs/other/webservers.md
- provisioning/requirements.yml
Fixes #781 which is solved upstream but not yet referenced in requirements. Also adds an optional user/group param for php-fpm.
> Adds optional defaults for php-fpm user & group.

- docs/other/drupalvm-composer-dependency.md
If this makes sense in the first place, please let me know if the wording needs to change.
- Without either adding devel as a dependency to composer.json, or
removing devel from drupal_enabled_modules in config.yml, vagrant up
hangs when enabling modules.
- gh-792
> Adds drupal_enabled_modules info to composer section

- README.md
- default.config.yml
- docs/extras/elasticsearch.md
- provisioning/playbook.yml
- provisioning/requirements.yml
Adds elasticsearch to installed extras.
Note:
For use on the host outside vagrant will depend on an upstream change like in PR's 9 or 17 or equivalent.
> Add elasticsearch to installed extras

- default.config.yml
- provisioning/tasks/build-makefile.yml
I needed to be able to customize the drush make command line options for a project. So, I added the ability to completely override the options used during provisioning. I think others may find it useful as well.
> Add ability to override drush make command line options.

- Vagrantfile
When using the id argument for vagrant halt to act on a vagrant installation in a different directory a warning is currently generated.  This is due to the VAGRANTFILE_API_VERSION already being define.  This PR checks if it has been defined.
Warnings - 
```
Vagrantfile:3: warning: already initialized constant VAGRANTFILE_API_VERSION
```
```
Vagrantfile:3: warning: previous definition of VAGRANTFILE_API_VERSION was here
```
> vagrant halt [id] causes "warning: already initialized constant VAGRANTFILE_API_VERSION"

- default.config.yml
Hey @geerlingguy I just updated drupal-vm default var per https://github.com/arknoll/ansible-role-selenium/pull/8. It solves my problem, which seemed to be the same as #843 so I added the closing command in the commit message (but of course let me know if that's not cool – you could always squash on commit and change it if you want).
Just for extra info, I ran into this trying to install Behat on drupal-vm release 3.2.0, following [Docs » Extra Software and Setup » Test with Behat and Selenium » Getting Started - Installing Prerequisites](http://docs.drupalvm.com/en/latest/extras/behat/#getting-started-installing-prerequisites).
> Update default Selenium version to latest. Fixes #843

- .travis.yml
Rubocop 0.44.0 introduced `Metric/BlockLength` https://github.com/bbatsov/rubocop/blob/master/CHANGELOG.md#0440-2016-10-13.
Travis failure:
https://travis-ci.org/geerlingguy/drupal-vm/jobs/167887473#L328
> Disable rubocop block length check

- provisioning/tasks/init-redhat.yml
I kept the functionality for
> Makes sense, if you want to use a different repo.
With this change you cannot disable the repo though.
> Fixes #925, Followup #859: Remi repo is not enabled for mysql by default

- Vagrantfile
- default.config.yml
This commit allows the sync folder sharing type for the location of vagrant cachier to be
configured. It also sets it to 'nfs' as default.
> Issue #950: Allow sync folder type for cachier location to be configured

- provisioning/tasks/init-debian.yml
> Remove deprecated PPA ondrej/php5.

- Vagrantfile
Haven't had time to manually verify this fix yet.
> Issue #912: Fix Vagrant 1.8.6 failing to mount synced folders with empty mount_options

- .travis.yml
- tests/config.yml
- tests/ubuntu-16-postgresql.config.yml
There's really no reason to test the extra utilities for the pgsql integration test as everything has already been tested in the default scenario.
I also removed the xhprof integration test so we don't have to define the `installed_extras` variable but can reuse it from `default.config.yml`. I imagine we're mostly interested in knowing that the virtual hosts are created in all scenarios and we already test that with adminer and PML.
> Remove duplicate integration tests

- Vagrantfile
- provisioning/playbook.yml
This would allow for
```sh
vagrant provision
DRUPALVM_ENV=prod vagrant provision --provider=aws
DRUPALVM_ENV=prod ansible-playbook -i examples/prod/inventory provisioning/playbook.yml --sudo --ask-sudo-pass
ansible-playbook -i examples/prod/inventory provisioning/playbook.yml --sudo --ask-sudo-pass
ansible-playbook -i examples/prod/inventory provisioning/playbook.yml --sudo --ask-sudo-pass
```
Precedence from low to high:
1. `default.config.yml`
2. `config.yml`
3. `local.config.yml`
4. `{{ DRUPALVM_ENV }}.config.yml`
> Issue #455: Allow for environment specific config files

- docs/other/overriding-configurations.md
The plugin already supports environment variables (`VAGRANT_HTTP_PROXY` etc) so I excluded those from @morsok original PR.
I keep piling docs into that _Overriding configurations_ section as I'm hesitant to create new topics 😄
> Fixes #847, Followup #848: Add docs on using vagrant-proxyconf

- docs/extras/syncing-folders.md
I just realized the issue described in #872 is actually outdated docs. You can now override `owner` and `group` using `options_override`. This closes #872.
> Fixes #872: Update synced folder troubleshooting docs taking into account options_override

- docs/other/production.md
- mkdocs.yml
A first draft of the functionality.
> Issue #455: Add docs on environment specific configs

- default.config.yml
- provisioning/playbook.yml
- provisioning/requirements.yml
- provisioning/roles/thom8.php-upload-progress/.travis.yml
- provisioning/roles/thom8.php-upload-progress/README.md
- provisioning/roles/thom8.php-upload-progress/defaults/main.yml
- provisioning/roles/thom8.php-upload-progress/meta/main.yml
- provisioning/roles/thom8.php-upload-progress/tasks/main.yml
- provisioning/roles/thom8.php-upload-progress/templates/uploadprogress.ini.j2
- provisioning/roles/thom8.php-upload-progress/tests/Dockerfile.centos-7
- provisioning/roles/thom8.php-upload-progress/tests/Dockerfile.ubuntu-12.04
- provisioning/roles/thom8.php-upload-progress/tests/Dockerfile.ubuntu-14.04
- provisioning/roles/thom8.php-upload-progress/tests/inventory
- provisioning/roles/thom8.php-upload-progress/tests/test-source.yml
- provisioning/roles/thom8.php-upload-progress/tests/uploadprogress-test.php
- provisioning/roles/thom8.php-upload-progress/vars/Debian.yml
- provisioning/roles/thom8.php-upload-progress/vars/RedHat.yml
Add role to install the uploadprogress extension -- https://pecl.php.net/package/uploadprogress
role :: https://github.com/beetboxvm/ansible-role-beetbox-upload-progress
> Added upload-progress role.

- Vagrantfile
- docs/other/overriding-configurations.md
Added docs to @joestewart PR #820. The docs section might not be ideal.
> Followup #820: Pass ansible arguments via environment variable if provided.

- Vagrantfile
I was about to set up some wildcard vhosts when hostsupdater threw this:
```
==> drupalvm_project: [vagrant-hostsupdater] Checking for host entries
==> drupalvm_project: [vagrant-hostsupdater]   found entry for: 192.168.99.88 drupalvm-project.dev
/Users/cindy/.vagrant.d/gems/gems/vagrant-hostsupdater-1.0.2/lib/vagrant-hostsupdater/HostsUpdater.rb:80: warning: nested repeat operator '+' and '*' was replaced with '*' in regular expression
/Users/cindy/.vagrant.d/gems/gems/vagrant-hostsupdater-1.0.2/lib/vagrant-hostsupdater/HostsUpdater.rb:39: warning: nested repeat operator '+' and '*' was replaced with '*' in regular expression
/Users/cindy/.vagrant.d/gems/gems/vagrant-hostsupdater-1.0.2/lib/vagrant-hostsupdater/HostsUpdater.rb:39: warning: nested repeat operator '+' and '*' was replaced …
```
> Fix hostsupdater trying to add wildcard aliases

- examples/prod/bootstrap/init.yml
The variable is listed in `example.vars.yml` but never actually used in the playbook.
> Fix prod/bootstrap/init not taking into account admin_copy_ssh_pubkey

- provisioning/playbook.yml
Currently, if you use a loop inside a post/pre-provision taskfile ansible will complain if you use the `item` variable.
> [WARNING]: The loop variable 'item' is already in use. You should set the
`loop_var` value in the `loop_control` option for the task to something else to
avoid variable collisions and unexpected behavior.
This makes DX a bit nicer by allowing the users to use that variable.
> Allow post-provision tasks to use the item variable

- provisioning/templates/dashboard.html.j2
At least for apache this property is optional. I excluded it as I wanted `VirtualDocumentRoot` rather than `DocumentRoot` and with that setup, the dashboard template caused the provision to fail.
> Fix bug where dashboard assumes optional vhost docroot is defined

- provisioning/playbook.yml
At the moment Drupal VM does not use ansible tags out of the box, but I wanted to use it for my own custom post-provision tasks. By default all the pre/post-provision tasks are excluded as the include statements are without tags.
This PR fixes the issue by delegating the decision of tags to the post-provision scripts. Rather than setting the tag to `user-provision` or something similar, I think they should be set it to `always` so that users can take full advantage of tags. http://docs.ansible.com/ansible/playbooks_tags.html#special-tags
```sh
DRUPALVM_ANSIBLE_ARGS='--tags=foobar' vagrant provision
```
Currently I'm only tagging the config includes and the post/pre-provision tasks. But maybe we should also tag _Include OS-specific variables._ and such?
> Allow user defined post-provision-tasks to use tags while drupal vm does not

- Vagrantfile
- provisioning/playbook.yml
Feature discussed in https://github.com/geerlingguy/drupal-vm/pull/1070#discussion_r93670548.
Example if requirement would be `2.3`:
```
drupal-vm cindy@cindy ansible-min-version*: vagrant status
/Users/cindy/Projects/Personal/drupal-vm/Vagrantfile:146:in `block in <top (required)>': You must update Ansible to at least 2.3 to use this version of Drupal VM. (RuntimeError)
from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/config/v2/loader.rb:37:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/config/v2/loader.rb:37:in `load'
from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/config/loader.rb:113:in `block (2 levels) in load'
from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/config/loader.rb:107:in `each'
from …
```
> Move ansible version requirements to Vagrantfile for better UX

- provisioning/vars/Debian.yml
- provisioning/vars/RedHat.yml
This is still entirely untested. Hopefully I'll get time to locally test it later today.
> Issue #1068: Add php-yaml as a default php package

- default.config.yml
- provisioning/playbook.yml
Would be nicer if this could be done upstream in the php extension roles though... Now stuff such as solr is rebuilt as well.
> Fix PHP modules not re-compiling on PHP version changes

- default.config.yml
- provisioning/templates/nginx-vhost.conf.j2
Adding the PR for travis as well as further review and discussion.
_Status reports only complaint is that trusted hosts settings is disabled._
_Added Zen and http://drupalvm.dev/themes/contrib/zen/STARTERKIT/styleguide/ displays `index.html`_
> curl -I http://drupalvm.dev/install.php
HTTP/1.1 301 Moved Permanently
> 
_Adding `install_site: false` and running the installation through `/install.php` adds the `rewrite=ok` GET parameter._
> Use SetHandler fixing mod_rewrite and DirectoryIndex issues

- examples/scripts/configure-solr.sh
This pull request has implemented the suggestion I raised in #1133
> Create new solr collection instead of using the default one.

- default.config.yml
Simple change to link to new documentation page location.
http://docs.drupalvm.com/en/latest/configurations/php/
> Link to new page for php version documentation.

- docs/configurations/base-os.md
Since firewalld does not exist for CentOS 6, the Drupal VM `firewall_disable_firewalld` setting, which defaults to `true`, must be overridden in `config.yml` and set to `false`.
Also, this commit organizes the CentOS 6 notes into bullets.
> Add note about firewalld on CentOS 6

- Vagrantfile
- docs/extending/ansible-args.md
I refactored the provisioner declaration so that it's more DRY. Doesnt matter much now but maybe if we add SKIP_TAGS or some more config variables in the future.
> Follow-up #1213: Add support for DRUPALVM_ANSIBLE_TAGS env variable

- docs/getting-started/syncing-folders.md
While reading through the synced folder docs I also tested out one of the examples that seemed incorrect. NFS does not support `dmode` or `fmode`, and produces an invalid mount command. Also `owner`/`group` doesn't affect NFS.
> Issue #1199: Fix synced folder examples in docs

- provisioning/tasks/drush-aliases.yml
We forgot this one in the last major release.
> Remove configure_local_drush_aliases shim

- Vagrantfile
I thought this was nicer and less confusing, what do you think?
old
```sh
$ vagrant status
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.
Path: /Users/cindy/Projects/Personal/drupal-vm/Vagrantfile
Line number: 77
Message: RuntimeError: You must update Ansible to at least 2.2 to use this version of Drupal VM.
```
new
```sh
$ vagrant status
You must update Ansible to at least 2.2 to use this version of Drupal VM.
```
> Raise a VagrantError rather than a RuntimeError for clearer message

- provisioning/tasks/www.yml
This is still WIP. Not the nicest solution and it needs proper testing.
Using `stat.gr_name` would be way nicer and could remove the shell task, unfortunately I can't get this to work though. It's never defined in my case.
Also, if the user sets `vagrant_synced_folder_default_type` to something other than `nfs` while using `nfs` for the primary synced folder, this wont help. Other than that I don't see this causing issues. Maybe with smb somehow?
> Issue #1220: Fix to ensure www-data is in the same group as NFS synced dirs

- provisioning/templates/drupalvm.aliases.drushrc.php.j2
Fixes having a VAAGRANT_HOME set to a different directory.
> Use VAGRANT_HOME to get ssh key directory

- Vagrantfile
Just posting ideas...
```sh
==> drupalvm_project: Mounting NFS shared folders...
==> drupalvm_project: Mounting shared folders...
drupalvm_project: /var/www/drupalvm => /Users/cindy/Projects/Personal/drupal-vm
==> drupalvm_project: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> drupalvm_project: flag to force provisioning. Provisioners marked to run always will still run.
==> drupalvm_project: Machine 'drupalvm_project' has a post `vagrant up` message. This is a message
==> drupalvm_project: from the creator of the Vagrantfile, and not from Vagrant itself:
==> drupalvm_project:
==> drupalvm_project: Your Drupal VM Vagrant box is ready to use!
==> drupalvm_project: * Visit the dashboard for an overview of your site: http://dashboard.drupalvm-project.dev …
```
> Add an intro message for vagrant up/reload

- docs/getting-started/installation-linux.md
I felt it was too hidden away when added to the numbered list of possible fixes. I think an encrypted home directory is pretty common so rather highlight this as the first debugging step.
> Issue #1289: Add encryption as a possible cause for NFS issues on linux

- docs/other/performance.md
See https://github.com/geerlingguy/drupal-vm/issues/1242#issuecomment-289130181.
How's that? Or maybe under the synced folder section as it's more a feature than a performance improvement suggestion
> Add docs on how to improve performance by mixing synced folder types

- provisioning/tasks/init-debian.yml
Before:
```
TASK [Purge PHP version packages.] *********************************************
[WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: 'php{{ php_version }}' not in item
```
After:
```
TASK [Purge PHP version packages.] *********************************************
ok: [drupalvm_project] => (item=[u'php5.6', u'php5.6-apcu', u'php5.6-cli', u'php5.6-common', u'php5.6-curl', u'php5.6-dev', u'php5.6-fpm', u'php5.6-gd', u'php5.6-imap', u'php5.6-json', u'php5.6-mbstring', u'php5.6-mcrypt', u'php5.6-opcache', u'php5.6-sqlite3', u'php5.6-xml', u'php5.6-yaml', u'php7.0', u'php7.0-apcu', u'php7.0-cli', u'php7.0-common', u'php7.0-curl', u'php7.0-dev', u'php7.0-fpm', u'php7.0-gd', u'php7.0-imap', u'php7.0-json', u'php7.0-mbstring', …
```
> Fix Ansible 2.3 not purging PHP packages because of jinja templating in when statement

- provisioning/playbook.yml
Let's see if it passes. Maybe better to revert the upstream commit but wanted to check.
> Issue #1313: Redefine geerlingguy.drupal handler due to ansible bug

- provisioning/roles/drupalvm.www/README.md
- provisioning/roles/drupalvm.www/meta/main.yml
Or should we use:
```yaml
dependencies:
- { role: geerlingguy.nginx, when: drupalvm_webserver == 'nginx' }
```
> Issue #1324: Remove geerlingguy.nginx hard dependency from drupalvm.www

- docs/other/wordpress-other-applications.md
- mkdocs.yml
As Drupal VM is so flexible I thought it would be useful to point this out in the docs. Included an example to integrate it with the [bedrock project](https://github.com/roots/bedrock).
> Add docs on using Drupal VM with other application eg Wordpress

- .travis.yml
- Vagrantfile
- lib/drupalvm/vagrant.rb
Inspired by https://github.com/roots/trellis/pull/828.
A first stab at a simple Vagrantfile logic split. Thoughts?
> Vagrantfile cleanup

- docs/deployment/composer.md
- example.drupal.composer.json
Sets example.composer.json to use "web" directory.
Updates documentation references from "docroot" to "web".
> Fixes #1351

- default.config.yml
Updating default node version to `6.x` which is the same as the [role default](https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/roles/geerlingguy.nodejs/defaults/main.yml).
Therefore, it could potentially be removed from `default.config.yml` but it might be useful to keep so it exposes the config.
Relates to #1348
> Update default node version to 6.x

- Vagrantfile
- docs/getting-started/installation-linux.md
How about leveraging the same logic as we already use for `vagrant_synced_folders`?
```
vagrant_synced_folders:
- local_path: .
destination: /var/www/drupalvm
type: nfs
create: true
- local_path: .
destination: /vagrant
type: rsync
options_override: [...]
```
Would need to add docs for this though.
> Issue #1375: Allow /vagrant synced folder to be overridden

- docs/extras/xdebug.md
- provisioning/tasks/sshd.yml
- provisioning/templates/drupalvm.aliases.drushrc.php.j2
> Issue #1171: Allow client to pass PHP and XDEBUG environemnt variables over SSH

- default.config.yml
I've been hit by php segfaults due to having XHProf installed on old projects I bump to PHP 7.1.
Also XHProf was the cause for at least these two issues:
- https://github.com/geerlingguy/drupal-vm/issues/1285
- https://github.com/geerlingguy/drupal-vm/issues/1341
> Add note about tideways rather than xhprof to default.config.yml

- docs/configurations/php.md
- provisioning/playbook.yml
Built successfully with this `config.yml` on Ubuntu 16.04:
```yaml
---
php_version: ''
installed_extras:
- adminer
- blackfire
- drush
- mailhog
- memcached
- pimpmylog
- redis
- tideways
- upload-progress
- varnish
- xdebug
```
That last sentence in the docs might need some tuning.
> Issue 1418: Allow default distribution php packages to be used

- examples/scripts/configure-solr.sh
Still says it is set up for D7, but is set up for D8.
> Update comment in Solr post-provisioning script

- provisioning/playbook.yml
Might need testing in older versions of Ansible but at least as of 2.3.1.0 this has backwards compatibility. This is also what we added to [`geerlingguy.mac-dev-playbook`](https://github.com/geerlingguy/mac-dev-playbook/pull/43/files) btw.
> Issue #1437: Add support for list of paths in pre/post_provision_tasks_dir

- default.config.yml
Just found the outdated comment in `default.config.yml`.
The variable has been renamed in #1193
> Fix outdated comment for drupal_install_site variable

- default.config.yml
- docs/deployment/composer-dependency.md
I think knowing about `{{ playbook_dir }}` and `{{ config_dir }}` makes it easier for users to reason about the paths. Counting parent directories is a headache.
> Use absolute paths for example post_provision_scripts

- Vagrantfile
Linked clones are only enabled on vagrant versions `1.8.x`, updates to enable of all versions greater than `1.8`
> Enable linked_clone on versions greater than 1.8.

- tests/run-tests.sh
Print body and headers if a test fails. Let's see what mailhog says.
- `-i` show headers in output
- `-I` fetch headers only
- `-s` hide progress bar (and error messages unless `-S`)
- `-S` show error messages.
> Improve debug output in travis

- provisioning/templates/dashboard.html.j2
Hi Jeff,
firstly thank you for all your energy you put into this project. 
We have recently switched to it and so far it is really great experience.
As time goes I've added multiple sites with db's to my VM and the dashboard start to look full and confusing. I've also realized that parts of the dashboard are used more often then others.
This pull request is only changing the dashboard template (provisioning/templates/dashboard.html.j2).
- Make all tables responsive, to prevent overlapping of content even on desktop.
- Add stripes to some tables.
- Fixed logo position/size on small screen.
- Cleaner header.
- First row – Site and DB list's. 
- DB list is much simpler.
- Second row – Technical info (DB Info, PHP info, Development tools).
- Third row – Host file content.
- All new styling is …
> Reorganization of the dashboard with small styling update.

- mkdocs.yml
Menu item should be "tideways" rather than "tidways"
> Update mkdocs.yml to fix typo

- default.config.yml
Normally, the NPM version installed by Node out of the box is pretty out of date.
This PR will cause it to automatically be updated to the latest available version (respective to whatever version of Node you are using). This is recommended and considered best practice by Node/NPM.
> Update NPM by default

- default.config.yml
Hello,
During an update of my local install of DrupalVm I noticed a few outdated referenced variables in the comments of the default.config.yml. This pull request updates them.
> Update referenced variables in comments

- default.config.yml
The base box has been adjusted to work with Drupal VM so provisioning tasks will skip is they've been preprovisioned..
> Add beet/box as an available base box.

- docs/extras/selenium.md
With behat 3.4.3, the example config gives the following error on behat --init:
The reserved indicator "%" cannot start a plain scalar; you need to quote the scalar at line 4 (near "paths: [ %paths.base%/features/web ]").
This is fixed by quoting the paths value.
> Selenium paths value needs to be quoted

- lib/drupalvm/vagrant.rb
When ansible is installed from repository version string is like: 
`ansible 2.4.3.0 (stable-2.4 8708105616) `
Instead of:
`ansible 2.4.3.0`
Regexp fails because it includes the part in parenthesis. Added new regexp that ignores that part. See http://rubular.com/r/J4TBshh16b to see it working.
> Make ansible version parsing compatible with releases from git repository

- default.config.yml
This is a follow up to https://github.com/geerlingguy/ansible-role-php-xdebug/pull/47
As indicated in that issue, `php_xdebug_cli_enable` is no longer used and references to it should be removed.
However, it's being replaced by a new option `php_xdebug_cli_disable` in https://github.com/geerlingguy/ansible-role-php-xdebug/pull/54. So it might make sense to just switch one for the other.
> php_xdebug_cli_enable is unused

- docs/extras/tideways.md
I was trying to set up Tideways recently and got pretty confused because it wasn't clear what the relationship was between the Tideways extension and the native XHProf extension, especially given that Tideways recently split and now is called the "Tideways XHProf extension" :roll_eyes: 
Hopefully this clears things up a little.
> Clean up Tideways documentation

- provisioning/roles/geerlingguy.drupal/tasks/build-composer.yml
A bug was introduced in commit e8664798e08421db9fc85edfadaf7958750a8907 that causes composer install to fail when drupalVM was added as a dependency to an existing site.
> Fixed typo in build-composer.yml that caused composer install to fail

- provisioning/playbook.yml
Tags don't seem to be inherited with `include_tasks` so switch to `import_tasks` to work on #1835
> Change include_tasks to import_tasks for always tasks.

- examples/scripts/pareview.sh
For examples/scripts/pareview.sh:
DrupalSecure Code Sniffs git url changed after the move to Gitlab repositories.
https://www.drupal.org/project/1921926/git-instructions provides the examples with the url https://git.drupalcode.org/sandbox/coltrane-1921926.git
> Update sandbox url after drupal.org git change [ci-skip]

- docs/other/docker.md
Error: `In SiteInstallCommands.php line 367: Failed to drop or create the database:`
This is due because the `systemctl start mysql` command failed due to missing volume. Fix was to add the missing volume to the command.
Also, resolves #1856
> Fixes site-install error.

- default.config.yml
For Mac developers using [Homebrew](https://brew.sh/), this edit will be helpful as most of them won't have Python 3 in `/usr/bin`
> 🐍 point to the Python 3 interpreter in PATH

- default.config.yml
Include php_xdebug_version in default.config.yml to provide visibility to this option.
> Include php_xdebug_version in default.config.yml

- README.md
First ever pull request - please be gentle:)
I got very confused trying to override the default Drupal 9 installation. I'm proposing an addition to the README to add some clarification. It's far from perfect, there are a couple of additions I would like to make but don't know how to
1. I don't understand the relationship between drupal_major_version and drupal_composer_project_package. drupal_major_version seems to have no affect on the default install, but somewhere on the web (can't find it now) it is the recommended solution. Perhaps just an update to the default.config.yml to link the two variables together would help?
2, I would like to add a pointer to the available versions e.g. https://www.drupal.org/project/drupal/releases or  "For a specific version, use …
> Update README.md - installing Drupal 8

- default.config.yml
- docs/other/wordpress-other-applications.md
- examples/scripts/pareview.sh
Fixes #2099 
I don't know if there is a more sophisticated way to deal with this, but by default, Composer 2.x is installed on new projects, and this solution got me past the provisioning error. Composer 2 has `hirak/prestissimo` 's parallel download feature built in now.
> Fixes #2099: Prestissimo not needed with Composer 2.x

- example.drupal.composer.json
Long time-user, first-time pull requester. I found some errors trying to copy and use the composer.json in ./example.drupal.composer.json and this commit fixes them.
> Fixes syntax errors in example.drupal.composer.json #2094

- Vagrantfile
This fixes an issue that was recently created by the release of a new version of the script here: https://bootstrap.pypa.io/get-pip.py.
TL;DR — they dropped support for Python2 and this now requires pip3. Maybe worth noting I may have had to manually install Python3 via SSH into the box, but I may have also already had it and it was a step I just duplicated. Either way — this fixes issues folks should be having as of this last Saturday.
> fix: add ansible install_mode "pip3"

- docs/getting-started/syncing-folders.md
- docs/other/performance.md
Another option is to only set `type` if truthy.
> Fixes #2144: Change docs on native synced folders to use explicit type
