geerlingguy/drupal-vm

README.md
It wasn't clear in what directory you should run the galaxy install command so I switched the order of steps to make this explicit.
=> Clarify where to install Ansible Galaxy roles

provisioning/playbook.yml
So that you for example could install `unzip` and extract zip files in your drush makefile.
=> Move up installation of any extra packages

docs/Catch-Emails-with-MailHog.md, docs/Cloning-Drupal-VM-with-newd.md, docs/Connect-to-the-MySQL-Database.md, docs/Debug-Code-with-XDebug.md, docs/Drupal-6-Notes.md, docs/Drupal-multisite.md, docs/Drush-Make-file.md, docs/Local-Drupal-codebase.md, docs/PHP-7-on-Drupal-VM.md, docs/Profile-Code-with-XHProf.md, docs/Syncing-Folders.md, docs/Test-with-Behat-and-Selenium.md, docs/Use-Apache-Solr-for-Search.md, docs/Use-Drupal-Console-with-Drupal-VM.md, docs/Use-Drush-with-Drupal-VM.md, docs/Use-MariaDB-instead-of-MySQL.md, docs/Use-Varnish-with-Drupal-VM.md, docs/Using-Different-Base-OSes.md, docs/View-Logs-with-Pimp-my-Log.md, docs/Windows-Notes.md, docs/index.md, docs/mkdocs.yml
1. Moves docs to `/docs` directory
2. Stubs out mkdocs.yml with sane defaults
3. Renames Home.md to index.md for mkdocs standard
=> Moving docs

provisioning/tasks/drush-aliases.yml, provisioning/templates/drupalvm-local.aliases.drushrc.php.j2
Relates to https://github.com/geerlingguy/drupal-vm/issues/156
=> Add drush alias within vm.

docs/extras/pimpmylog.md
I was configuring PML and stumbled upon some small issues. 
Regarding the added note about permissions; I wasn't sure on how you would like to handle this. I chose to add a note to the docs, because I think it's something very depending on one's purpose of using Drupal VM (as a local dev env, mimic a production env, etc).
=> Fix formatting and add note about permission settings on some log files.

provisioning/playbook.yml, provisioning/tasks/sshd.yml
Not sure where you'd prefer having this?
=> Issue #186: Do not accept locale environment variables passed over SSH

example.config.yml
Added spaces inside the apache vhost objects(?) so that they are consistent with the rest of the codebase.
=> Added spaces

docs/deployment/local-codebase.md, example.config.yml
=> Fixed references to misnamed property "build_from_makefile".

docs/extras/mysql.md
=> Fix typo in mysql.md.

docs/extras/behat.md
* Updated behat.yml to include the needed contexts to load and use the DrupalExtension driver.
* Updated behat.yml to include region mapping for content region so the DrupalExtension could find it.
* Updated examples to point to features/web since that is what behat.yml is set up for.
* Added syntax to code fences to help fix formatting on the web page.
=> Updates to examples and syntax highlighting.

docs/extras/syncing-folders.md
Here's a new PR, following on from #277.
=> Add documentation and example of rsync excluded_paths

example.config.yml
Followup to 43da06d92316eebb2abbecd813a4d5dc74a279fc
=> Remove 'id' from code comment

provisioning/templates/nginx-vhost.conf.j2
See related issue: https://github.com/geerlingguy/drupal-vm/issues/350
=> Fixes #350: Update Nginx vhost template for more optimal Drupal 8 usage.

docs/extras/xdebug.md
Thanks for making Drupal VM!  It is awesome and I was hoping to contribute back.
=> Update xdebug.md for NetBeans Configuration

.travis.yml, provisioning/tasks/apparmor.yml, tests/Dockerfile.ubuntu-14.04, tests/initctl_faker
=> Add custom initctl script for fixing docker tests on ubuntu 14.04

.travis.yml, example.config.yml, provisioning/vars/main.yml, tests/test-vars.yml
https://github.com/geerlingguy/ansible-role-composer/issues/17
=> Fixes #495: Set composer owner to vagrant user

example.config.yml
Fixes https://github.com/geerlingguy/drupal-vm/issues/540.
To save others the same experience if they only read the quickstart guide. :smile:
=> Issue #540: Clarify PHP 7 requirements.

example.config.yml, provisioning/tasks/init-debian.yml, provisioning/tasks/init-redhat.yml
The package is small and I don't really see a use case for someone not wanting it. What do you think?
=> Issue #550: Make unzip a dependency

example.config.yml
This depends on https://github.com/geerlingguy/ansible-role-nodejs/pull/23 getting merged.
=> Fixes #424: Fix NPM packages being installed under root user

docs/deployment/local-codebase.md, docs/extras/drush.md
Do not merge yet. We need testing and possible docs for windows.
=> [WIP] Issue #406: Add docs about sql-sync workaround for older drush versions

docs/extras/newrelic.md, example.config.yml, provisioning/playbook.yml, provisioning/requirements.yml
Here's an initial stab at New Relic support. Untested. CC @cweagans
=> New Relic support, conditionally-installed

README.md, ansible.cfg
See: https://github.com/geerlingguy/drupal-vm/issues/505
=> Fixes #505: Add ansible.cfg file to set a roles_path in Drupal VM directory

README.md, Vagrantfile, docs/other/overriding-configurations.md, docs/other/php-7.md
https://github.com/geerlingguy/drupal-vm/issues/608#issuecomment-218793792
=> Followup #608: Automate ansible-galaxy install step

.gitignore, .travis.yml, Vagrantfile, provisioning/JJG-Ansible-Windows/README.md, provisioning/JJG-Ansible-Windows/windows.sh, provisioning/requirements.yml, tests/local.config.yml, tests/ubuntu-16-nginx.config.yml
See: https://github.com/geerlingguy/drupal-vm/issues/616
=> Issue #616: Re-enable the XHProf integration test.

docs/extras/scripts.md, provisioning/playbook.yml
The first sentence is probably the longest in history but not enough sleep to think clearly at the moment.
=> PR #623: Add support for custom pre/post ansible tasks.

Vagrantfile
See https://github.com/geerlingguy/drupal-vm/issues/702
=> Fixes #702: Include default vagrant-cachier configuration.

example.drupal.composer.json
Followup #699. Also opened a PR at drupal-project. https://github.com/drupal-composer/drupal-project/pull/159
=> Use packages.drupal.org composer repository in example

default.config.yml, provisioning/requirements.yml
See upstream issue: https://github.com/geerlingguy/ansible-role-mailhog/issues/3
=> Switch from ssmtp to mhsendmail.

docs/extras/drupal-console.md
throws a Symfony Exception if you're not in the correct directory
=> added /web to the directory

README.md
See http://parallels.github.io/vagrant-parallels/ (bottom of the page).
=> Document that Parallels requires paid version.

Vagrantfile, default.config.yml
=> Allow forcing ansible local

.gitignore, provisioning/roles/franklinkim.newrelic/tasks/config.yml
Fixes issue #845 where the user gets a "Deprecation Warning" - Replacing the missing config.yml file from franklinkim.newrelic fixes this.
=> Fix for issue #845 - missing role config file for franklinkim.newrelic

provisioning/templates/drupalvm.vcl.j2
description here: 
https://github.com/geerlingguy/drupal-vm/issues/947
=> I think the PURGE request needs to return (purge);

docs/js/fix_search.js, mkdocs.yml
I've only been able to test this by pasting it into the console and that does work.
Fix adapted from https://github.com/rtfd/readthedocs.org/issues/1088#issuecomment-224715045
=> Fix ReadTheDocs search feature

docs/extras/ssl.md, mkdocs.yml
This is using @joestewart example https://github.com/geerlingguy/drupal-vm/issues/754#issuecomment-242744098, which worked when I tested it on Ubuntu 16.04.
---
I thought the magic jinja trick might be useful so I added a tips & tricks section. Prefer if I leave it out?
=> Add docs on using HTTPS with Nginx

examples/prod/prod.config.yml
That should be the last one :)
=> Followup #1090: Use SetHandler in prod config example

examples/prod/prod.config.yml
https://github.com/geerlingguy/drupal-vm/pull/1105#issuecomment-270815501
=> Follow-up #1093: Disable apache package upgrades in prod example config

provisioning/templates/nginx-vhost.conf.j2
=> Fixes #1158, Follow-up #1086: Fix Drupal 7 and nginx breaking install.php

default.config.yml, provisioning/requirements.yml, provisioning/roles/geerlingguy.drupal/README.md, provisioning/roles/geerlingguy.drupal/defaults/main.yml, provisioning/roles/geerlingguy.drupal/tasks/install-site.yml, provisioning/roles/geerlingguy.drupal/tasks/main.yml, provisioning/roles/geerlingguy.drupal/tests/requirements.yml, provisioning/roles/geerlingguy.drupal/tests/test.yml
=> 1212 drush make

default.config.yml
=> Switch to set PHP's default to 7.1

docs/configurations/php.md
=> Update the docs to state 7.1 is the default

provisioning/playbook.yml, provisioning/tasks/init-redhat.yml, provisioning/tasks/php.yml
Now when all the drupal stuff is moved to it's own role (:tada:) the playbook feels so clean. Here's a few cleanup suggestions.
=> Cleanup playbook

Vagrantfile, docs/getting-started/syncing-folders.md
See https://github.com/geerlingguy/drupal-vm/issues/1199#issuecomment-287633956
=> Issue #1199: Fix options_override causing duplicate json entries

Vagrantfile, docs/deployment/composer-dependency.md
See #1231. This looks for the `Vagrantfile.local` in both `host_project_dir` and `host_config_dir`.
=> Look for Vagrantfile.local in both project_dir and config_dir

docs/getting-started/installation-linux.md
Changed "certain ports are protocols" to "certain ports or protocols" for clarity.
=> Minor grammar fix

provisioning/vars/main.yml
=> Issue #1302: Remove ansible_ssh_user variable to avoid upstream bugs

provisioning/playbook.yml
This reverts commit 4420d52cbd8675df6b5c9b3520c68778b01bdf30.
=> Issue #1314: Revert "Move simple include_vars statement to vars_files"

provisioning/playbook.yml
=> Always include OS specific variables

README.md, default.config.yml, docs/configurations/webservers-nginx.md, docs/deployment/multisite.md, docs/extras/drush.md, docs/extras/varnish.md, examples/prod/prod.config.yml, lib/drupalvm/vagrant.rb, provisioning/playbook.yml, provisioning/roles/drupalvm.www/tasks/main.yml, provisioning/tasks/backwards-compatibility.yml, provisioning/tasks/drush-aliases.yml, provisioning/templates/dashboard.html.j2, provisioning/templates/drupalvm-local.aliases.drushrc.php.j2, provisioning/templates/drupalvm.aliases.drushrc.php.j2, provisioning/templates/drupalvm.vcl.j2, provisioning/templates/nginx-vhost.conf.j2
~This is entirely untested so still WIP.~
=> Allow provided templates to be extended through template inheritance

default.config.yml, docs/extras/xdebug.md
This solves the `Remote host is configured as 'localhost' despite server host is probably not local` problem in the validator. See http://stackoverflow.com/a/36152477/721065
Forgive me if I didn't follow the editing procedure correctly 😬
=> to pass the Web Server Debug Validation

provisioning/templates/nginx-vhost.conf.j2
Just a PR, I haven't tested this. @yobottehg could you verify if this works?
=> Issue #1368: Fix private files not accessable with nginx

provisioning/templates/nginx-vhost.conf.j2
Verified with these https://www.drupal.org/node/2408321#comment-11904864
https://www.nginx.com/resources/wiki/start/topics/recipes/drupal/
=> Issue #1424: Add support for RFC 5785 with nginx

.gitignore
Not entirely sure when this was added to git but it's definitely been in for a while. Somewhere between ~1.9.3 and 2.2.1~
=> Issue #1411: Fix gitignore applying rules to files in subdirectories

Vagrantfile, docs/getting-started/installation-linux.md, docs/getting-started/syncing-folders.md
This needs manual testing to verify if it in fact fixes #1468. Also worth comparing build performance on macOS. I'll run a few builds and post my own results.
=> Issue #1468: Fix various Linux issues with NFS by defaulting to TCP

example.drupal.make.yml
Updating drupal.make.yml file to the latest version of Drupal, 8.3.4.
=> Updating to latest Drupal build 8.3.4

docs/other/docker.md
Had my IP in there, may confuse someone.
=> IP consistency

Vagrantfile, docs/extending/ansible-args.md
https://gist.github.com/phantomwhale/9657134
This always bothered me.
=> Use shellwords hack to allow spaces in DRUPALVM_ANSIBLE_ARGS

docs/extras/xdebug.md
From PR https://github.com/geerlingguy/drupal-vm/pull/1631.
=> Add "Atom and XDebug with Drupal VM" section

docs/other/production.md
I grabbed the text for this change from: https://www.jeffgeerling.com/blog/2017/soup-nuts-using-drupal-vm-build-local-and-prod
=> Add an example of what to put in secrets.yml

docs/extras/drush.md
Related to https://github.com/geerlingguy/drupal-vm/issues/1894.
=> Drush instead of Drupal

docs/extras/solr.md
Hi there, the link to find solr config specs is broken in master. Thanks for your work on this project!
=> Fix broken link in solr docs

provisioning/roles/geerlingguy.adminer/tasks/main.yml
=> Issue #2183: Minor typo
